// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBr0aGWQDu-dYCLxzgBRMihD8Fb5uELwjM',
    appId: '1:580682843069:web:f38348597eb833b7a708d4',
    messagingSenderId: '580682843069',
    projectId: 'mozaik-16497',
    authDomain: 'mozaik-16497.firebaseapp.com',
    storageBucket: 'mozaik-16497.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdqW0k3vjOVDPHfIyyZhhD7JWry4todT0',
    appId: '1:580682843069:android:dd00de2538234b54a708d4',
    messagingSenderId: '580682843069',
    projectId: 'mozaik-16497',
    storageBucket: 'mozaik-16497.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASrihu8QCVv6CQ5yLMPkd4qNs4HsQ0x9k',
    appId: '1:580682843069:ios:ac6ed0725c857e3fa708d4',
    messagingSenderId: '580682843069',
    projectId: 'mozaik-16497',
    storageBucket: 'mozaik-16497.firebasestorage.app',
    iosClientId: '580682843069-gj8kgeign313k77jegd5hdmlolka3hdj.apps.googleusercontent.com',
    iosBundleId: 'com.example.mozaik',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASrihu8QCVv6CQ5yLMPkd4qNs4HsQ0x9k',
    appId: '1:580682843069:ios:ac6ed0725c857e3fa708d4',
    messagingSenderId: '580682843069',
    projectId: 'mozaik-16497',
    storageBucket: 'mozaik-16497.firebasestorage.app',
    iosClientId: '580682843069-gj8kgeign313k77jegd5hdmlolka3hdj.apps.googleusercontent.com',
    iosBundleId: 'com.example.mozaik',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBr0aGWQDu-dYCLxzgBRMihD8Fb5uELwjM',
    appId: '1:580682843069:web:745991460a6fa99da708d4',
    messagingSenderId: '580682843069',
    projectId: 'mozaik-16497',
    authDomain: 'mozaik-16497.firebaseapp.com',
    storageBucket: 'mozaik-16497.firebasestorage.app',
  );

}